import typer
import requests
from bs4 import BeautifulSoup
from requests.exceptions import Timeout, ConnectionError
from typing import Dict, Tuple, List
from concurrent.futures import ThreadPoolExecutor

# Timeout-Wert für HTTP-Anfragen (in Sekunden)
REQUEST_TIMEOUT = 20

# Dictionary containing platform names as keys and URLs with placeholders for the username
links = {
    "AniWorld": "https://aniworld.to/user/profil/{}",
    "CyberDefenders": "https://cyberdefenders.org/p/{}0",
    "DeviantART": "https://{}.deviantart.com",
    "Fiverr": "https://www.fiverr.com/{}",
    "HackerEarth": "https://hackerearth.com/@{}",
    "NitroType": "https://www.nitrotype.com/racer/{}",
    "Reddit": "https://www.reddit.com/user/{}",
    "Roblox": "https://www.roblox.com/user.aspx?username={}",
    "Smule": "https://www.smule.com/{}",
    "Snapchat": "https://www.snapchat.com/add/{}",
    "Star Citizen": "https://robertsspaceindustries.com/citizens/{}",
    "Twitch": "https://www.twitch.tv/{}",
    "Zhihu": "https://www.zhihu.com/people/{}",
    "forum_guns": "https://forum.guns.ru/forummisc/blog/{}",
    "2Dimensions": "https://2Dimensions.com/a/{}",
    "7Cups": "https://www.7cups.com/@{}",
    "9GAG": "https://www.9gag.com/u/{}",
    "About.me": "https://about.me/{}",
    "Academia.edu": "https://independent.academia.edu/{}",
    "Alik.cz": "https://www.alik.cz/u/{}",
    "Apple Discussions": "https://discussions.apple.com/profile/{}",
    "Asciinema": "https://asciinema.org/~{}",
    "Ask Fedora": "https://ask.fedoraproject.org/u/{}",
    "AskFM": "https://ask.fm/{}",
    "Audiojungle": "https://audiojungle.net/user/{}",
    "BLIP.fm": "https://blip.fm/{}",
    "Bandcamp": "https://www.bandcamp.com/{}",
    "Bazar.cz": "https://www.bazar.cz/{}/",
    "Behance": "https://www.behance.net/{}",
    "BitBucket": "https://bitbucket.org/{}/",
    "Blogger": "https://{}.blogspot.com",
    "Bookcrossing": "https://www.bookcrossing.com/mybookshelf/{}/",
    "BuyMeACoffee": "https://buymeacoff.ee/{}",
    "BuzzFeed": "https://buzzfeed.com/{}",
    "CNET": "https://www.cnet.com/profiles/{}/",
    "Carbonmade": "https://{}.carbonmade.com",
    "Career.habr": "https://career.habr.com/{}",
    "Championat": "https://www.championat.com/user/{}",
    "Chatujme.cz": "https://profil.chatujme.cz/{}",
    "Chess": "https://www.chess.com/member/{}",
    "CloudflareCommunity": "https://community.cloudflare.com/u/{}",
    "Codecademy": "https://www.codecademy.com/profiles/{}",
    "Codepen": "https://codepen.io/{}",
    "Codewars": "https://www.codewars.com/users/{}",
    "ColourLovers": "https://www.colourlovers.com/lover/{}",
    "Contently": "https://{}.contently.com/",
    "Coroflot": "https://www.coroflot.com/{}",
    "Crevado": "https://{}.crevado.com",
    "DEV Community": "https://dev.to/{}",
    "DailyMotion": "https://www.dailymotion.com/{}",
    "Designspiration": "https://www.designspiration.net/{}/",
    "DeviantART": "https://{}.deviantart.com",
    "Discogs": "https://www.discogs.com/user/{}",
    "Discuss.Elastic.co": "https://discuss.elastic.co/u/{}",
    "Disqus": "https://disqus.com/{}",
    "Dribbble": "https://dribbble.com/{}",
    "Ello": "https://ello.co/{}",
    "Etsy": "https://www.etsy.com/shop/{}",
    "EyeEm": "https://www.eyeem.com/u/{}",
    "F3.cool": "https://f3.cool/{}/",
    "Facebook": "https://www.facebook.com/{}",
    "Facebook Groups": "https://www.facebook.com/groups/{}",
    "Fandom": "https://www.fandom.com/u/{}",
    "Fiverr": "https://www.fiverr.com/{}",
    "Flickr": "https://www.flickr.com/people/{}",
    "Flipboard": "https://flipboard.com/@{}",
    "Football": "https://www.rusfootball.info/user/{}/",
    "FortniteTracker": "https://fortnitetracker.com/profile/all/{}",
    "Freelance.habr": "https://freelance.habr.com/freelancers/{}",
    "Freelancer.com": "https://www.freelancer.com/u/{}",
    "Freesound": "https://freesound.org/people/{}/",
    "Gamespot": "https://www.gamespot.com/profile/{}/",
    "GetMyUni": "https://www.getmyuni.com/user/{}",
    "Giphy": "https://giphy.com/{}",
    "GitHub": "https://www.github.com/{}",
    "GitHub Support Community": "https://github.community/u/{}/summary",
    "GitLab": "https://gitlab.com/{}",
    "Gitee": "https://gitee.com/{}",
    "GoodReads": "https://www.goodreads.com/{}",
    "Gravatar": "http://en.gravatar.com/{}",
    "Gumroad": "https://www.gumroad.com/{}",
    "GunsAndAmmo": "https://forums.gunsandammo.com/profile/{}",
    "GuruShots": "https://gurushots.com/{}/photos",
    "HackTheBox": "https://forum.hackthebox.eu/profile/{}",
    "Hackaday": "https://hackaday.io/{}",
    "HackerOne": "https://hackerone.com/{}",
    "Houzz": "https://houzz.com/user/{}",
    "HubPages": "https://hubpages.com/@{}",
    "ICQ": "https://icq.im/{}",
    "IFTTT": "https://www.ifttt.com/p/{}",
    "ImgUp.cz": "https://imgup.cz/{}",
    "Instagram": "https://instagram.com/{}",
    "Instructables": "https://www.instructables.com/member/{}",
    "Issuu": "https://issuu.com/{}",
    "Itch.io": "https://{}.itch.io/",
    "Jimdo": "https://{}.jimdosite.com",
    "Kaggle": "https://www.kaggle.com/{}",
    "Keybase": "https://keybase.io/{}",
    "Kik": "https://kik.me/{}",
    "Kongregate": "https://www.kongregate.com/accounts/{}",
    "LOR": "https://www.linux.org.ru/people/{}/profile",
    "Launchpad": "https://launchpad.net/~{}",
    "LeetCode": "https://leetcode.com/{}",
    "Letterboxd": "https://letterboxd.com/{}",
    "Lichess": "https://lichess.org/@/{}",
    "Likee": "https://likee.com/@{}",
    "LiveJournal": "https://{}.livejournal.com",
    "Lobsters": "https://lobste.rs/u/{}",
    "Medium": "https://medium.com/@{}",
    "Memrise": "https://www.memrise.com/user/{}/",
    "Munzee": "https://www.munzee.com/m/{}",
    "MyAnimeList": "https://myanimelist.net/profile/{}",
    "MyMiniFactory": "https://www.myminifactory.com/users/{}",
    "Myspace": "https://myspace.com/{}",
    "NameMC (Minecraft.net skins)": "https://namemc.com/profile/{}",
    "Naver": "https://blog.naver.com/{}",
    "Newgrounds": "https://{}.newgrounds.com",
    "NotABug.org": "https://notabug.org/{}",
    "OK": "https://ok.ru/{}",
    "OpenStreetMap": "https://www.openstreetmap.org/user/{}",
    "Opensource": "https://opensource.com/users/{}",
    "PCPartPicker": "https://pcpartpicker.com/user/{}",
    "Pastebin": "https://pastebin.com/u/{}",
    "Patreon": "https://www.patreon.com/{}",
    "Periscope": "https://www.periscope.tv/{}/",
    "Pinkbike": "https://www.pinkbike.com/u/{}/",
    "PlayStore": "https://play.google.com/store/apps/developer?id={}",
    "Plug.DJ": "https://plug.dj/@/{}",
    "Pokémon Showdown": "https://pokemonshowdown.com/users/{}",
    "Polygon": "https://www.polygon.com/users/{}",
    "ProductHunt": "https://www.producthunt.com/@{}",
    "PromoDJ": "http://promodj.com/{}",
    "PyPi": "https://pypi.org/user/{}",
    "Quizlet": "https://quizlet.com/{}",
    "Quora": "https://www.quora.com/profile/{}",
    "Raidforums": "https://raidforums.com/User-{}",
    "Rajce.net": "https://{}.rajce.idnes.cz/",
    "RapidAPI": "https://rapidapi.com/users/{}",
    "Rate Your Music": "https://rateyourmusic.com/~{}",
    "Redbubble": "https://www.redbubble.com/people/{}",
    "Repl.it": "https://repl.it/@{}",
    "ResearchGate": "https://www.researchgate.net/profile/{}",
    "ReverbNation": "https://www.reverbnation.com/{}",
    "Roblox": "https://www.roblox.com/user.aspx?username={}",
    "RubyGems": "https://rubygems.org/profiles/{}",
    "Sbazar.cz": "https://www.sbazar.cz/{}",
    "Scratch": "https://scratch.mit.edu/users/{}",
    "Scribd": "https://www.scribd.com/{}",
    "ShitpostBot5000": "https://www.shitpostbot.com/user/{}",
    "Signal": "https://community.signalusers.org/u/{}",
    "Slack": "https://{}.slack.com",
    "Slashdot": "https://slashdot.org/~{}",
    "SlideShare": "https://slideshare.net/{}",
    "Snapchat": "https://snapchat.com/add/{}",
    "SoundCloud": "https://soundcloud.com/{}",
    "SourceForge": "https://sourceforge.net/u/{}",
    "Speedrun.com": "https://speedrun.com/user/{}",
    "Splits.io": "https://splits.io/users/{}",
    "Sporcle": "https://www.sporcle.com/user/{}/people",
    "SportsRU": "https://www.sports.ru/profile/{}/",
    "Spotify": "https://open.spotify.com/user/{}",
    "Star Citizen": "https://robertsspaceindustries.com/citizens/{}",
    "SublimeForum": "https://forum.sublimetext.com/u/{}",
    "Tellonym.me": "https://tellonym.me/{}",
    "Test PyPi": "https://test.pypi.org/user/{}",
    "TikTok": "https://tiktok.com/@{}",
    "Ultimate-Guitar": "https://ultimate-guitar.com/u/{}",
    "Unsplash": "https://unsplash.com/@{}",
    "VK": "https://vk.com/{}",
    "VSCO": "https://vsco.co/{}",
    "Venmo": "https://venmo.com/{}",
    "Vero": "https://vero.co/{}",
    "Vimeo": "https://vimeo.com/{}",
    "VirusTotal": "https://www.virustotal.com/ui/users/{}/trusted_users",
    "Warrior Forum": "https://www.warriorforum.com/members/{}.html",
    "Wattpad": "https://www.wattpad.com/user/{}",
    "We Heart It": "https://weheartit.com/{}",
    "WebNode": "https://{}.webnode.cz/",
    "Whonix Forum": "https://forums.whonix.org/u/{}",
    "Wikipedia": "https://www.wikipedia.org/wiki/User:{}",
    "Windy": "https://community.windy.com/user/{}",
    "Wix": "https://{}.wix.com",
    "WordPressOrg": "https://profiles.wordpress.org/{}/",
    "Xbox Gamertag": "https://xboxgamertag.com/search/{}",
    "YouPic": "https://youpic.com/photographer/{}/",
    "YouTube": "https://www.youtube.com/{}",
    "Zhihu": "https://www.zhihu.com/people/{}",
    "Akniga": "https://akniga.org/profile/{}",
    "AllMyLinks": "https://allmylinks.com/{}",
    "AminoApp": "https://aminoapps.com/u/{}",
    "authorSTREAM": "http://www.authorstream.com/{}/",
    "babyRU": "https://www.baby.ru/u/{}/",
    "chaos.social": "https://chaos.social/@{}",
    "CouchSurfing": "https://www.couchsurfing.com/people/{}",
    "d3RU": "https://d3.ru/user/{}/posts",
    "Dailykos": "https://www.dailykos.com/user/{}",
    "datingRU": "http://dating.ru/{}",
    "Drive2": "https://www.drive2.ru/users/{}",
    "eGPU": "https://egpu.io/forums/profile/{}/",
    "Eintracht": "https://community.eintracht.de/fans/{}",
    "Fixya": "https://www.fixya.com/users/{}",
    "FL": "https://www.fl.ru/users/{}",
    "GeoCaching": "https://www.geocaching.com/p/default.aspx?u={}",
    "Habr": "https://habr.com/ru/users/{}",
    "Hackster": "https://www.hackster.io/{}",
    "irecommend": "https://irecommend.ru/users/{}",
    "Jeuxvideo": "http://www.jeuxvideo.com/profil/{}?mode=infos",
    "Kofi": "https://ko-fi.com/{}",
    "kwork": "https://kwork.ru/user/{}",
    "Last.fm": "https://last.fm/user/{}",
    "LeaseHackr": "https://forum.leasehackr.com/u/{}/summary/",
    "LiveLib": "https://www.livelib.ru/reader/{}",
    "mastodon.cloud": "https://mastodon.cloud/@{}",
    "mastodon.social": "https://mastodon.social/@{}",
    "Mercadolivre": "https://www.mercadolivre.com.br/perfil/{}",
    "Moikrug": "https://moikrug.ru/{}",
    "Mstdn.io": "https://mstdn.io/@{}",
    "Nairaland.com": "https://www.nairaland.com/{}",
    "nnRU": "https://{}.www.nn.ru/",
    "Note": "https://note.com/{}",
    "npm": "https://www.npmjs.com/~{}",
    "Opennet": "https://www.opennet.ru/~{}",
    "Osu!": "https://osu.ppy.sh/users/{}",
    "satsisRU": "https://satsis.info/user/{}",
    "social.tchncs.de": "https://social.tchncs.de/@{}",
    "Svidbook": "https://www.svidbook.ru/user/{}",
    "uid": "http://uid.me/{}",
    "Nextcloud Forum": "https://help.nextcloud.com/u/{}/summary/",
    "Nightbot": "https://nightbot.tv/t/{}/commands/",
    "Ninja Kiwi": "https://ninjakiwi.com/profile/{}",
    "NintendoLife": "https://www.nintendolife.com/users/{}",
    "NitroType": "https://www.nitrotype.com/racer/{}",
    "NotABug.org": "https://notabug.org/{}",
    "Nyaa.si": "https://nyaa.si/user/{}",
    "OpenStreetMap": "https://www.openstreetmap.org/user/{}",
    "Opensource": "https://opensource.com/users/{}",
    "OurDJTalk": "https://ourdjtalk.com/members?username={}",
    "PCGamer": "https://forums.pcgamer.com/members/?username={}",
    "PSNProfiles.com": "https://psnprofiles.com/{}",
    "Packagist": "https://packagist.org/packages/{}/",
    "Pastebin": "https://pastebin.com/u/{}",
    "Patreon": "https://www.patreon.com/{}",
    "PentesterLab": "https://pentesterlab.com/profile/{}",
    "PepperIT": "https://www.pepper.it/profile/{}/overview",
    "Periscope": "https://www.periscope.tv/{}/",
    "Pinkbike": "https://www.pinkbike.com/u/{}/",
    "PlayStore": "https://play.google.com/store/apps/developer?id={}",
    "PocketStars": "https://pocketstars.com/{}",
    "Pokemon Showdown": "https://pokemonshowdown.com/users/{}",
    "Polarsteps": "https://polarsteps.com/{}",
    "Polygon": "https://www.polygon.com/users/{}",
    "Polymart": "https://polymart.org/user/{}",
    "Pornhub": "https://pornhub.com/users/{}",
    "ProductHunt": "https://www.producthunt.com/@{}",
    "PromoDJ": "http://promodj.com/{}",
    "PyPi": "https://pypi.org/user/{}",
    "Rajce.net": "https://{}.rajce.idnes.cz/",
    "Rarible": "https://rarible.com/marketplace/api/v4/urls/{}",
    "Rate Your Music": "https://rateyourmusic.com/~{}",
    "Rclone Forum": "https://forum.rclone.org/u/{}",
    "RedTube": "https://www.redtube.com/users/{}",
    "Redbubble": "https://www.redbubble.com/people/{}",
    "Reddit": "https://www.reddit.com/user/{}",
    "Reisefrage": "https://www.reisefrage.net/nutzer/{}",
    "Replit.com": "https://replit.com/@{}",
    "ResearchGate": "https://www.researchgate.net/profile/{}",
    "ReverbNation": "https://www.reverbnation.com/{}",
    "Roblox": "https://www.roblox.com/user.aspx?username={}",
    "RocketTube": "https://www.rockettube.com/{}",
    "RoyalCams": "https://royalcams.com/profile/{}",
    "RubyGems": "https://rubygems.org/profiles/{}",
    "Rumble": "https://rumble.com/user/{}",
    "Kaggle": "https://www.kaggle.com/{}",
    "Kaskus": "https://www.kaskus.co.id/@{}",
    "Keybase": "https://keybase.io/{}",
    "Kick": "https://kick.com/{}",
    "Kik": "https://kik.me/{}",
    "Kongregate": "https://www.kongregate.com/accounts/{}",
    "Linux.org.ru": "https://www.linux.org.ru/people/{}/profile",
    "Launchpad": "https://launchpad.net/~{}",
    "Leetcode": "https://leetcode.com/{}",
    "Lesswrong": "https://www.lesswrong.com/users/@{}",
    "Letterboxd": "https://letterboxd.com/{}",
    "LibraryThing": "https://www.librarything.com/profile/{}",
    "Lichess": "https://lichess.org/@/{}",
    "LinkedIn": "https://linkedin.com/in/{}",
    "Linktree": "https://linktr.ee/{}",
    "Listed.to": "https://listed.to/@{}",
    "Livejournal": "https://{}.livejournal.com",
    "Lobste.rs": "https://lobste.rs/u/{}",
    "Lottiefiles": "https://lottiefiles.com/{}",
    "LushStories": "https://www.lushstories.com/profile/{}",
    "MMORPG": "https://forums.mmorpg.com/profile/{}",
    "Medium": "https://medium.com/@{}",
    "Memrise": "https://www.memrise.com/user/{}/",
    "Mojang": "https://api.mojang.com/users/profiles/minecraft/{}",
    "Mixcloud": "https://www.mixcloud.com/{}/",
    "MonkeyType": "https://monkeytype.com/profile/{}",
    "Motherless": "https://motherless.com/m/{}",
    "Motorradfrage": "https://www.motorradfrage.net/nutzer/{}",
    "MyAnimeList": "https://myanimelist.net/profile/{}",
    "MyMinifactory": "https://www.myminifactory.com/users/{}",
    "MyDramaList": "https://www.mydramalist.com/profile/{}",
    "MySpace": "https://myspace.com/{}",
    "Native Instruments": "https://community.native-instruments.com/profile/{}",
    "NationStates (Nation)": "https://nationstates.net/nation={}",
    "NationStates (Region)": "https://nationstates.net/region={}",
    "Naver": "https://blog.naver.com/{}",
    "Needrom": "https://www.needrom.com/author/{}/",
    "Newgrounds": "https://{}.newgrounds.com",
    "RusFootball": "https://www.rusfootball.info/user/{}/",
    "FortniteTracker": "https://fortnitetracker.com/profile/all/{}",
    "Forumophilia": "https://www.forumophilia.com/profile.php?mode=viewprofile&u={}",
    "Fosstodon": "https://fosstodon.org/@{}",
    "Freelance Habr": "https://freelance.habr.com/freelancers/{}",
    "Freelancer": "https://www.freelancer.com/u/{}",
    "Freesound": "https://freesound.org/people/{}/",
    "GitLab GNOME": "https://gitlab.gnome.org/{}",
    "GaiaOnline": "https://www.gaiaonline.com/profiles/{}",
    "GameSpot": "https://www.gamespot.com/profile/{}/",
    "GeeksForGeeks": "https://auth.geeksforgeeks.org/user/{}",
    "Genius (Artists)": "https://genius.com/artists/{}",
    "Genius (User)": "https://genius.com/{}",
    "Gesundheitsfrage": "https://www.gesundheitsfrage.net/nutzer/{}",
    "GetMyUni": "https://www.getmyuni.com/user/{}",
    "GiantBomb": "https://www.giantbomb.com/profile/{}/",
    "Giphy": "https://giphy.com/{}",
    "Gitbook": "https://{}.gitbook.io/",
    "GitHub": "https://www.github.com/{}",
    "GitLab (General)": "https://gitlab.com/{}",
    "Gitea": "https://gitea.com/{}",
    "Gitee": "https://gitee.com/{}",
    "Goodreads": "https://www.goodreads.com/{}",
    "Play Store": "https://play.google.com/store/apps/developer?id={}",
    "Gradle Plugins": "https://plugins.gradle.org/u/{}",
    "Grailed": "https://www.grailed.com/{}",
    "Gravatar": "http://en.gravatar.com/{}",
    "Gumroad": "https://www.gumroad.com/{}",
    "Gutefrage": "https://www.gutefrage.net/nutzer/{}",
    "HackTheBox Forum": "https://forum.hackthebox.com/u/{}",
    "Hackaday": "https://hackaday.io/{}",
    "Hackenproof": "https://hackenproof.com/hackers/{}",
    "HackerEarth": "https://hackerearth.com/@{}",
    "Hacker News": "https://news.ycombinator.com/user?id={}",
    "HackerOne": "https://hackerone.com/{}",
    "HackerRank": "https://hackerrank.com/{}",
    "Harvard Scholar": "https://scholar.harvard.edu/{}",
    "Hashnode": "https://hashnode.com/@{}",
    "Heavy-R": "https://www.heavy-r.com/user/{}",
    "Holopin": "https://holopin.io/@{}",
    "Houzz": "https://houzz.com/user/{}",
    "HubPages": "https://hubpages.com/@{}",
    "Hubski": "https://hubski.com/user/{}",
    "Cavalier HudsonRock": "https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-username?username={}",
    "HuggingFace": "https://huggingface.co/{}",
    "IFTTT": "https://www.ifttt.com/p/{}",
    "IRC Galleria": "https://irc-galleria.net/user/{}",
    "Icons8 Community": "https://community.icons8.com/u/{}/summary",
    "ImageFap": "https://www.imagefap.com/profile/{}",
    "ImgUp": "https://imgup.cz/{}",
    "Imgur": "https://imgur.com/user/{}",
    "Instagram": "https://instagram.com/{}",
    "Instructables": "https://www.instructables.com/member/{}",
    "Intigriti": "https://app.intigriti.com/profile/{}",
    "Ionic Framework Forum": "https://forum.ionicframework.com/u/{}",
    "Issuu": "https://issuu.com/{}",
    "Itch.io": "https://{}.itch.io/",
    "ItemFix": "https://www.itemfix.com/c/{}",
    "Jellyfin": "https://translate.jellyfin.org/user/{}/",
    "JimdoSite": "https://{}.jimdosite.com",
    "JoplinApp": "https://discourse.joplinapp.org/u/{}"
}

def check_link_exists(link: str, username: str) -> Tuple[str, str]:
    try:
        response = requests.get(link.format(username), timeout=REQUEST_TIMEOUT)
        if response.status_code == 200:
            return "success" if username.lower() in response.text.lower() else "error", link.format(username)
        else:
            return "error", ""
    except (Timeout, ConnectionError):
        return "timeout", ""

def check_username(platform: str, link: str, username: str) -> Tuple[str, str, str]:
    status, found_link = check_link_exists(link, username)
    return platform, status, found_link

def check_usernames(username: str) -> Tuple[Dict[str, str], List[str]]:
    results = {}
    found_links = []
    with ThreadPoolExecutor() as executor:
        futures = [executor.submit(check_username, platform, link, username) for platform, link in links.items()]
        for future in futures:
            platform, status, found_link = future.result()
            results[platform] = status
            if status == "success":
                found_links.append(found_link)
    return results, found_links

def print_results(results: Dict[str, str], found_links: List[str]):
    for platform, status in results.items():
        if status == "success":
            print(f"Profil auf {platform}: Erfolgreich")
        elif status == "error":
            print(f"Profil auf {platform}: Nicht gefunden")
        elif status == "timeout":
            print(f"Profil auf {platform}: Timeout beim Laden der Seite")
    if found_links:
        print("\nGefundene Links:")
        for link in found_links:
            print(link)

def main(username: str):
    print(r"""
                                   Created by
  _       _________ _                            _______  __    ______   ______  
 ( \      \__   __/( (    /||\     /||\     /|  (  ____ \/  \  (  __  \ / ___  \ 
 | (         ) (   |  \  ( || )   ( |( \   / )  | (    \/\/) ) | (  \  )\/   \  \
 | |         | |   |   \ | || |   | | \ (_) /   | |        | | | |   ) |   ___) /
 | |         | |   | (\ \) || |   | |  ) _ (    | |        | | | |   | |  (___ ( 
 | |         | |   | | \   || |   | | / ( ) \   | |        | | | |   ) |      ) \
 | (____/\___) (___| )  \  || (___) |( /   \ )  | (____/\__) (_| (__/  )/\___/  /
 (_______/\_______/|/    )_)(_______)|/     \|  (_______/\____/(______/ \______/ 
""")
    print("Scanning for profiles...")
    results, found_links = check_usernames(username)
    print_results(results, found_links)

if __name__ == "__main__":
    typer.run(main)
